#!/bin/bash

#this is a utkast for making the trimmomatic script, nothing is correct

#SBATCH -A uppmax2026-1-61  #project code 
#SBATCH -M pelle
#SBATCH -t 0-1:00:00 		# time limit
#SBATCH -J fastqc_1    #Job name
#SBATCH -c 1 		# number of cores
#SBATCH --mem 20G   # requested memory
#SBATCH -o %j.out			# File to which standard output will be written
#SBATCH -e %j.err 		# File to which standard error will be written

## Change directories to where the fastq files are located
cd ~/Analysis/Preprocessing_SLURM/

## Load modules required for script commands
module load FastQC/0.12.1-Java-17

## Run FASTQC
fastqc *illumina*
